version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./db-data:/app/db-data
    environment:
      - PORT=8080
      - JWT_SECRET=your_secure_jwt_secret_key_here
      - JWT_EXPIRATION=24h
      - DB_PATH=./db-data/auth.db
    restart: unless-stopped
    depends_on:
      - db

  db:
    image: busybox
    volumes:
      - ./db-data:/db
    command: "true"  # Just creates the volume

volumes:
  db-data:
    driver: local